### ISSUE TITLE
Changing frames in subsequent marker messages not handled correctly.

### ISSUE THREAD

**Issue by malban** [swri-robotics/mapviz#265]
Changing frames in subsequent marker messages not handled correctly.

The data appears to be displayed as if it was with respect to the frame of the first message.

**Comment by pjreed** [comment]
I looked into this, and the cause is pretty obvious; the plugin sets its source_frame_ member variable the first time a message is received, and mapviz uses that to transform the contents, and its value is never changed again unless you change the topic name.

It looks like there are actually several plugins that have this same behavior, so I'll fix all of them at once.
