### ISSUE TITLE
Exceptions in the Qt event handler cause Mapviz to crash

### ISSUE THREAD

**Issue by pjreed** [swri-robotics/mapviz#336]
Exceptions that are thrown by plugins in Qt's event handler will cause Mapviz to crash; see #327 for an example (although that issue should still be fixed so it doesn't happen in the first place).  Even if something bad happens, it would be better to log appropriately and keep running.

**Comment by cagataysari** [comment]
Hello I am not sure if it is directly related but I think that I am having a crash due to an unhandled event in MapApplication. I am running ROS Kinetic on Ubuntu 16.04 

Here is  the backtrace: 

(gdb) backtrace
#0  0x00007ffff7646f77 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x00007fffd8e22610 in QXcbConnection::handleXcbEvent(xcb_generic_event_t*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#2  0x00007fffd8e2305d in QXcbConnection::processXcbEvents() () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#3  0x00007fffef590c01 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff75ea05c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff75ef516 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff7b983af in mapviz::MapvizApplication::notify(QObject*, QEvent*) ()
   from /opt/ros/kinetic/lib/librqt_mapviz.so
#7  0x00007fffef56138b in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007fffef563786 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007fffef5b73c3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007fffeeab8197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007fffeeab83f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007fffeeab849c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007fffef5b77cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007fffef55eb4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007fffef566bec in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00000000004051e4 in main ()
(gdb)
