### ISSUE TITLE
Release into ROS Melodic

### ISSUE THREAD

**Issue by pjreed** [swri-robotics/mapviz#589]
This is currently waiting on [rosbridge_suite](https://github.com/RobotWebTools/rosbridge_suite/) to be released (see https://github.com/RobotWebTools/rosbridge_suite/issues/333 ) but after that should be ready to go.

**Comment by clalancette** [comment]
It looks like this was released into Melodic back on July 19th, which is great :+1: .  However, it looks like the version that was released doesn't compile because of the pluginlib backwards compatibility problem, i.e. http://build.ros.org/view/Mbin_ds_dS64/job/Mbin_ds_dS64__mapviz_plugins__debian_stretch_amd64__binary/14/consoleFull .  In the meantime, that particular problem was fixed in 3edb1cf5e71a4b841d0f5e278004b62130b84a72 .  I confirmed that it compiles locally now.  Could we have another release into Melodic to try and fix that?  Thanks!

**Comment by pjreed** [comment]
Oops, I actually thought I had made another release after that.  I'll do that shortly.

**Comment by pjreed** [comment]
Should be all done now.

**Comment by clalancette** [comment]
Excellent, thank you!
