### ISSUE TITLE
Path planning on mapviz

### ISSUE THREAD

**Issue by Hankyu-Kim** [swri-robotics/mapviz#782]
Hello I wanna make shortest path where is available to go only.
Because robot cannot across the water or building.
From where I am to final destination/sensor_msgs/NavSatFix. ( = LocalXY Origin - my_navsatfix_topic )

So, What I would like to ask you is the following.
1. How to mark the map data? i.e. 0 - restricted area 1 - avaiable path

reference : https://www.roguebasin.com/index.php/Dijkstra_Maps_Visualized

Best regards
Hankyu Kim

**Comment by danthony06** [comment]
Hello,

As I understand this, you are asking to do something like draw polygons on a map to indicate traversable areas. We don't currently have a plugin in like this, because we normally have a different node publish this information, rather than manually mark it. There are a few things I can point you at to help you decide on what you want to do:

- We do have a plugin for clicking in mapviz to generate a series of waypoints that form a route for a vehicle: https://github.com/swri-robotics/mapviz/blob/master/mapviz_plugins/src/plan_route_plugin.cpp.
- You could also have another node publish the information as a costmap, and Mapviz will display that with this plugin: https://github.com/swri-robotics/mapviz/blob/master/mapviz_plugins/src/occupancy_grid_plugin.cpp
- Finally, you might want to look into the costmap_2d package in ROS, I think this is what you're trying to make. It doesn't have a GUI to my knowledge, but it might be helpful for you to format the data in this way: http://wiki.ros.org/costmap_2d.
- You could also write a plugin for mapviz that lets you click on points to make a polygon, and then publish that as a costmap or occupancy grid.
